name: "Reusable workflow to deploy JSorolla application"

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
    secrets:
      SSH_TESTING_SERVER_HOST:
        required: true
      SSH_TESTING_SERVER_PORT:
        required: true
      SSH_TESTING_SERVER_USER:
        required: true
      SSH_TESTING_SERVER_PASSWORD:
        required: true

jobs:
  publish-test:
    name: Publish test results
    runs-on: ubuntu-22.04
    steps:
      - name: Download 'build' dir
        uses: actions/download-artifact@v3
        with:
          name: jsorolla-build
          path: build
      - name: Deploy unit tests web recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build
          remote: /var/www/html/iva/builds/${{ inputs.version }}
          host: ${{ secrets.SSH_TESTING_SERVER_HOST}}
          port: ${{ secrets.SSH_TESTING_SERVER_PORT}}
          username: ${{ secrets.SSH_TESTING_SERVER_USER }}
          password: ${{ secrets.SSH_TESTING_SERVER_PASSWORD }}
          concurrency: 2
