name: "Main development workflow"

on:
  push:
    branches:
      - "develop"
      - "release-*"

jobs:
  build:
    uses: opencb/jsorolla/.github/workflows/build-jsorolla-workflow.yml@release-2.4.x

  docker:
    needs: build
    uses: opencb/jsorolla/.github/workflows/docker-jsorolla-workflow.yml@release-2.4.x
    with:
      docker_tag: ${{ needs.build.outputs.version }}
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_ORGANISATION: ${{ secrets.DOCKER_HUB_ORGANISATION }}
      DOCKER_IMAGES_JSOROLLA: ${{ secrets.DOCKER_IMAGES_JSOROLLA }}
      JSOROLLA_CUSTOM_SITES_REPOSITORY: ${{ secrets.JSOROLLA_CUSTOM_SITES_REPOSITORY }}
      GH_PRIVATE_TOKEN: ${{ secrets.GH_PRIVATE_TOKEN }}
