name: "Main development workflow"

on:
  push:
    branches:
      - "develop"
      - "release-*"

jobs:
  build:
    uses: opencb/jsorolla/.github/workflows/build-jsorolla-workflow.yml@develop

  docker:
    needs: build
    uses: opencb/jsorolla/.github/workflows/docker-jsorolla-workflow.yml@develop
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_HUB_ORGANISATION: ${{ secrets.DOCKER_HUB_ORGANISATION }}
      DOCKER_IMAGES_JSOROLLA: ${{ secrets.DOCKER_IMAGES_JSOROLLA }}

  deploy:
    needs: build
    if: ${{ github.repository == 'opencb/jsorolla' }}
    uses: opencb/jsorolla/.github/workflows/deploy-jsorolla-workflow.yml@develop
    with:
      version: ${{ needs.build.outputs.version }}
    secrets:
      SSH_SWDEV_IP: ${{ secrets.SSH_SWDEV_IP }}
      SSH_SWDEV_USER: ${{ secrets.SSH_SWDEV_USER }}
      SSH_SWDEV_PASSWORD: ${{ secrets.SSH_SWDEV_PASSWORD }}
