name: "Develop branch workflow"

on:
  push:
    branches:
      - "develop"
      - "release-*"

jobs:
  build:
    uses: ./.github/workflows/build-jsorolla-workflow.yml

  test:
    uses: ./.github/workflows/test.yml
    needs: build
    with:
      test_profile: runShortTests
    secrets: inherit

  deploy-docker:
    uses: ./.github/workflows/deploy-docker-jsorolla.yml
    needs: test
    with:
      cli: python3 ./docker/docker-build.py push
    secrets: inherit

  deploy-web:
    uses: ./.github/workflows/deploy-jsorolla-web-workflow.yml
    needs: [ build, test ]
    with:
      version: ${{ needs.build.outputs.version }}
    secrets: inherit
