name: "Pull Request Workflow"

on:
  pull_request:
    branches:
      - "develop"
    types:
      - closed

jobs:
  docker-delete:
    name: Delete TASK docker image
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout JSorolla"
        uses: actions/checkout@v2
      - run: ./docker/docker-build.py delete --organisation ${{ secrets.DOCKER_HUB_ORGANISATION }} --image app --tag ${{ github.head_ref }} --username ${{ secrets.DOCKER_HUB_USER }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
