name: "Release"

on:
  push:
    tags:
      - "*"

jobs:
  build:
    uses: ./.github/workflows/build-jsorolla-workflow.yml

  test:
    uses: ./.github/workflows/test.yml
    needs: build
    secrets: inherit
    with:
      test_profile: runShortTests
      report_context: development

  deploy-docker:
    uses: ./.github/workflows/deploy-docker-jsorolla.yml
    needs: [ build, test ]
    with:
      repository: opencb/jsorolla
      branch: ${{ github.ref_name }}
      cli: python3 ./docker/docker-build.py push --tag ${{ needs.build.outputs.version }}
    secrets: inherit

  deploy:
    needs: [ build, test ]
    uses: ./.github/workflows/deploy-jsorolla-workflow.yml
    with:
      version: ${{ needs.build.outputs.version }}
    secrets: inherit

  release:
    needs: [build, test]
    uses: ./.github/workflows/release-github-workflow.yml
    with:
      artifact: jsorolla-release
      file: iva-${{ needs.build.outputs.version }}.tar.gz
