name: "Task Workflow for Task branches"

on:
  push:
    branches:
      - "TASK-*"

jobs:
  build:
    uses: opencb/jsorolla/.github/workflows/build-jsorolla-workflow.yml@develop

  test:
    uses: opencb/jsorolla/.github/workflows/test.yml@develop
    needs: build
    secrets: inherit

  deploy-docker:
    uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@develop
    needs: test
    with:
      repository: opencb/jsorolla
      branch: ${{ github.ref_name }}
      cli: python3 ./docker/docker-build.py push --tag ${{ github.ref_name }}
    secrets: inherit
