name: Build and test the project
on:
  workflow_call:
    inputs:
      test_profile:
        type: string
        required: true
      report_context:
        type: string
        required: true
    secrets:
      SONAR_TOKEN:
        required: true
      SSH_TESTING_SERVER_HOST:
        required: true
      SSH_TESTING_SERVER_PORT:
        required: true
      SSH_TESTING_SERVER_USER:
        required: true
      SSH_TESTING_SERVER_PASSWORD:
        required: true

env:
  xb_version: "1.7.0"

jobs:
  test:
    name: Test and push Sonar analysis
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm
          cache-dependency-path: 'package.json'
      - run: npm install
      - run: npm run test:prepare
      - uses: cypress-io/github-action@v5
        with:
          start: npm run serve
          command: npm run test:run
          browser: chrome
          wait-on: 'http://localhost:3000/src/sites/test-app/'
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: workdir
          path: |
            cypress/reports
            cypress/screenshots
            cypress/videos

  publish-test:
    name: Publish test results
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Download result dir
        uses: actions/download-artifact@v3
        with:
          name: workdir
          path: cypress
      - name: Deploy unit tests web recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: cypress
          remote: /var/www/html/reports/${{ inputs.report_context }}/${{ env.xb_version }}/${{ github.ref_name }}/jsorolla/${{ github.sha }}/unit/${{ matrix.module }}
          host: ${{ secrets.SSH_TESTING_SERVER_HOST}}
          port: ${{ secrets.SSH_TESTING_SERVER_PORT}}
          username: ${{ secrets.SSH_TESTING_SERVER_USER }}
          password: ${{ secrets.SSH_TESTING_SERVER_PASSWORD }}
          concurrency: 2
